# Generated by Django 3.2.4 on 2021-09-03 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0004_auto_20210622_0604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='фамилия')),
                ('phone', models.CharField(max_length=255, verbose_name='телефон')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('address', models.CharField(max_length=1024, verbose_name='адрес')),
                ('status', models.CharField(choices=[('new', 'Новый заказ'), ('in_progress', 'Заказ в обработке'), ('is_ready', 'Заказ готов'), ('completed', 'Заказ выполнен'), ('cancelled', 'Заказ отменен')], default='new', max_length=100, verbose_name='статус заказа')),
                ('buying_type', models.CharField(choices=[('self', 'Самовывоз'), ('delivery', 'Доставка курьером')], max_length=100, verbose_name='тип заказа')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий к заказу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания заказа')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления заказа')),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CartFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='количество')),
                ('price', models.SmallIntegerField(default=0, verbose_name='цена')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.food', verbose_name='блюдо')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_carts', to='orders.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'корзина блюд',
                'verbose_name_plural': 'корзины блюд',
            },
        ),
    ]
