# Generated by Django 3.2.4 on 2021-11-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20210622_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='description',
            field=models.TextField(max_length=512, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='name',
            field=models.CharField(max_length=64, verbose_name='шеф-повар'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='url',
            field=models.SlugField(max_length=128, unique=True, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='city_postcode',
            field=models.CharField(default='', max_length=128, verbose_name='город и почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(max_length=128, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='street_building',
            field=models.CharField(default='', max_length=128, verbose_name='улица и номер здания'),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(max_length=2048, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='food',
            name='in_menu',
            field=models.BooleanField(default=False, verbose_name='показывать в меню'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=128, verbose_name='блюдо'),
        ),
        migrations.AlterField(
            model_name='food',
            name='url',
            field=models.SlugField(max_length=128, unique=True, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='description',
            field=models.TextField(max_length=1024, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='name',
            field=models.CharField(max_length=128, verbose_name='кухня'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='url',
            field=models.SlugField(max_length=128, unique=True, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='restaurantimage',
            name='name',
            field=models.CharField(max_length=128, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(max_length=128, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.TextField(max_length=512, verbose_name='сообщение'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=128, verbose_name='имя'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_category'),
        ),
        migrations.AddConstraint(
            model_name='food',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_food'),
        ),
    ]
