# Generated by Django 3.1.7 on 2021-03-21 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantimage',
            options={'verbose_name': 'Фото ресторана'},
        ),
    ]
