# Generated by Django 3.2.4 on 2021-06-22 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20210622_0524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='шеф-повар')),
                ('age', models.PositiveSmallIntegerField(verbose_name='возраст')),
                ('description', models.TextField(max_length=300, verbose_name='описание')),
                ('image', models.ImageField(upload_to='chefs/', verbose_name='фото шеф-повара')),
                ('url', models.SlugField(max_length=100, unique=True, verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'шеф-повар',
                'verbose_name_plural': 'шеф-повара',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='блюдо')),
                ('description', models.TextField(verbose_name='описание')),
                ('price', models.PositiveSmallIntegerField(default=0, help_text='указывать сумму в рублях', verbose_name='цена')),
                ('image', models.ImageField(default='no_image.jpg', upload_to='food/', verbose_name='изображение')),
                ('url', models.SlugField(max_length=100, unique=True, verbose_name='ссылка')),
                ('in_menu', models.BooleanField(default=True, verbose_name='показывать в меню')),
            ],
            options={
                'verbose_name': 'блюдо',
                'verbose_name_plural': 'блюда',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('message', models.TextField(max_length=200, verbose_name='сообщение')),
                ('draft', models.BooleanField(default=True, verbose_name='черновик')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
            },
        ),
        migrations.RemoveField(
            model_name='chefs',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='category',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='kitchen',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'контактная информация', 'verbose_name_plural': 'контактная информация'},
        ),
        migrations.AlterModelOptions(
            name='kitchen',
            options={'verbose_name': 'кухня мира', 'verbose_name_plural': 'кухни мира'},
        ),
        migrations.AlterModelOptions(
            name='restaurantimage',
            options={'verbose_name': 'фото ресторана', 'verbose_name_plural': 'фото ресторана'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='city_postcode',
            field=models.CharField(default='', max_length=100, verbose_name='город и почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='contact_phone',
            field=models.CharField(max_length=16, verbose_name='контактный номер'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='from_hour_fri_sun',
            field=models.TimeField(default='11:00:00', verbose_name='время открытия Пт-Вс'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='from_hour_mon_thurs',
            field=models.TimeField(default='10:00:00', verbose_name='время открытия Пн-Чт'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='reservation_phone',
            field=models.CharField(max_length=16, verbose_name='номер для бронирования столиков'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='street_building',
            field=models.CharField(default='', max_length=100, verbose_name='улица и номер здания'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='to_hour_fri_sun',
            field=models.TimeField(default='02:00:00', verbose_name='время закрытия Пт-Вс'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='to_hour_mon_thurs',
            field=models.TimeField(default='23:00:00', verbose_name='время закрытия Пн-Чт'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='image',
            field=models.ImageField(default='no_image.jpg', upload_to='kitchen/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='name',
            field=models.CharField(max_length=100, verbose_name='кухня'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='url',
            field=models.SlugField(max_length=100, unique=True, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='restaurantimage',
            name='image',
            field=models.ImageField(upload_to='restaurant_image/', verbose_name='фото ресторана'),
        ),
        migrations.AlterField(
            model_name='restaurantimage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='имя'),
        ),
        migrations.DeleteModel(
            name='Chefs',
        ),
        migrations.DeleteModel(
            name='Foods',
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.category', verbose_name='категория блюда'),
        ),
        migrations.AddField(
            model_name='food',
            name='kitchen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.kitchen', verbose_name='кухня мира'),
        ),
        migrations.AddField(
            model_name='chef',
            name='kitchen',
            field=models.ManyToManyField(to='restaurant.Kitchen', verbose_name='кухня мира'),
        ),
    ]
