# Generated by Django 3.2.4 on 2021-09-01 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sessions', '0001_initial'),
        ('restaurant', '0004_auto_20210622_0604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16, verbose_name='номер телефона')),
                ('address', models.CharField(max_length=255, verbose_name='адрес')),
            ],
            options={
                'verbose_name': 'покупатель',
                'verbose_name_plural': 'покупатели',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='фамилия')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='телефон')),
                ('address', models.CharField(blank=True, max_length=1024, null=True, verbose_name='адрес')),
                ('status', models.CharField(choices=[('new', 'Новый заказ'), ('in_progress', 'Заказ в обработке'), ('is_ready', 'Заказ готов'), ('completed', 'Заказ выполнен'), ('cancelled', 'Заказ отменен')], default='new', max_length=100, verbose_name='статус заказа')),
                ('buying_type', models.CharField(choices=[('self', 'Самовывоз'), ('delivery', 'Доставка')], default='self', max_length=100, verbose_name='тип заказа')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий к заказу')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='дата создания заказа')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='дата обновления заказа')),
                ('final_price', models.IntegerField(default=0, verbose_name='финальная сумма')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to='orders.customer', verbose_name='покупатель')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_orders', to='sessions.session', verbose_name='сессия')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='order_customers', to='orders.Order', verbose_name='заказы покупателя'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.CreateModel(
            name='CartFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='количество')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='общая сумма')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.food', verbose_name='блюдо')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_carts', to='orders.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'корзина блюд',
                'verbose_name_plural': 'корзины блюд',
            },
        ),
    ]
